### ISSUE TITLE
things that happen because the trainer isn't updated yet 

### ISSUE THREAD

**Issue by frafflg** [MAFINS/MenyooSP#229]
some dlc cars disappear after they spawn , the stats in the player page don't work , sometimes the game don't find the character and we need to change clothes in the clothes section of the trainer in order for the character to make the triggers work , currently we can't add any vehicle to the favorites , currently can't save a set of clothes in the clothes section of the trainer , in some rare cases infinite health and no ragdoll don't work when inside the car , the trainer currently don't save each single setting but only a majority of it , so every time we actually need to open the trainer to set some things , but hey , if this get closed or deleted at least it will be the confirmation that the message is clear

**Comment by MAFINS** [comment]
These issues seem to be mentioned in issue thread #214
Hopefully someone can address them

**Comment by ToxxicFuse** [comment]
I'm getting tired of you spamming my inbox.
The trainer works completely fine, it just seems like you don't know how to set it up.


_"some dlc cars disappear after they spawn"_
**I think this is the only thing that you've said that might be caused by the update**


_"the stats in the player page don't work"_
**That's a know bug and this didn't working before the gta update**


_"sometimes the game don't find the character and we need to change clothes in the clothes section of the trainer in order for the character to make the triggers work"_
**This has nothing to do with the trainer not being updated, it's happening because you didn't follow the install instructions.**


_"currently we can't add any vehicle to the favorite"_
**This has nothing to do with the trainer not being updated, it's happening because you didn't follow the install instructions.**


_"currently can't save a set of clothes in the clothes section of the trainer"_
**This has nothing to do with the trainer not being updated, it's happening because you didn't follow the install instructions.**


_"in some rare cases infinite health and no ragdoll don't work when inside the car"_ 
**This, I didn't know, and it might be an actual bug.**


_"the trainer currently don't save each single setting but only a majority of it"_
**This has nothing to do with the trainer not being updated, it's happening because you didn't follow the install instructions.**


_"so every time we actually need to open the trainer to set some things"_
**This has nothing to do with the trainer not being updated, it's happening because you didn't follow the install instructions.**
