### ISSUE TITLE
Menyoo Object Spooner can't select some props

### ISSUE THREAD

**Issue by AuroraX11** [MAFINS/MenyooSP#327]
Some props are not selectable by Object Spooner (crosshair doesn't turn green).

I have checked the PropList.txt inside menyooStuff folder and the name of the props are there, however they are just not selectable :(

Example props; prop_cocktail , prop_tequila ..

I have checked and they have their collision as well. This happens even if I spawn the object with Menyoo itself.

**Comment by mistahwolf** [comment]
_"Some props are not selectable by Object Spooner (crosshair doesn't turn green).
I have checked the PropList.txt inside menyooStuff folder and the name of the props are there, however they are just not selectable :(
Example props; prop_cocktail , prop_tequila ..
I have checked and they have their collision as well. This happens even if I spawn the object with Menyoo itself."__

That happens with a lot of props. Especially those simulating glass. To get around that you have to go into spooner's database after you've spawned in the item and select it there and move it around with the coordinate toggles (x,y,z, etc.)

**Comment by AuroraX11** [comment]
> _"Some props are not selectable by Object Spooner (crosshair doesn't turn green). I have checked the PropList.txt inside menyooStuff folder and the name of the props are there, however they are just not selectable :( Example props; prop_cocktail , prop_tequila .. I have checked and they have their collision as well. This happens even if I spawn the object with Menyoo itself."__
> 
> That happens with a lot of props. Especially those simulating glass. To get around that you have to go into spooner's database after you've spawned in the item and select it there and move it around with the coordinate toggles (x,y,z, etc.)

Thank you very much for your reply <3 The problem though I meant the objects I didn't spawn with Menyoo's Object Spooner. For example I just want to delete an object I see in the world or change it's position however I am unable to do so, because those objects are not the ones spawned by Menyoo, they are just in the game world.

Though I guess what can I do is save the area to Menyoo database then clean the same distance entirely and then spawn everything I saved by using Menyoo and change their positions from Manage Entity Database. Not exactly practical but that is the only workaround that comes to my mind :(

**Comment by mistahwolf** [comment]
_"The problem though I meant the objects I didn't spawn with Menyoo's Object Spooner. For example I just want to delete an object I see in the world or change it's position however I am unable to do so, because those objects are not the ones spawned by Menyoo, they are just in the game world."_

Ah yes. Any prop you can't move is part of the map. Generally, if it's 'dynamic' you can probably select and delete it with Menyoo. However, if you 'save the database' you'll only be able to move those objects that were moveable before. You may even 'double up' those objects. To interact with map objects, you're going to need OIV and Codewalker. With OIV you can manually dig through the ymap and object files to remove things from the map. That's pretty messy and you can truly jack things up if you aren't precise. Codewalker is much more direct and you'll be able to make alternate maps of the areas you alter to put in the 'Mods' folder you'll have in OIV. Again, despite Codewalker's access to the game map you can completely f*** up your game if you don't know what you're doing. If you weren't aware, there are tons of YouTube vids on how to work both programs and you can get them at gta5mods.com.
