### ISSUE TITLE
So is Menyoo dead Mafins?

### ISSUE THREAD

**Issue by mistahwolf** [MAFINS/MenyooSP#333]
Love this trainer as it is the absolute best for building maps and characters. But '9 Months and two DLC updates' with nuthin' is telling you're done with this. I'm sure you're busy with other things, but this mod is bread and butter for those of us who rely heavily on it. If you would be kind enough to 'cut the rope on us' that would be swell. If you could slap out even a basic update that would be swell too!

cheers.

**Comment by MAFINS** [comment]
Unfortunately, I do not update this project anymore as I am busy with other things. I have not had access to the game this mod is built for for a good couple of years anyway. The reason this went open-source under the GPLv3 licence was so that the community could update this, whether via revival projects using forks (persuant to the licence terms) or by creating merge/pull requests so that the main project can be updated with commits made by multiple individuals.

I will leave this Issue up for a while instead of closing it so people can view this reply.

**Comment by mistahwolf** [comment]
That's too bad you no longer have a hand in it. However, since you say it's
now open source why is everyone complaining it's not? Also, how would one
go about getting permission to update it? Thanks for getting back btw.
