### ISSUE TITLE
Mafins is done. Who's going to step up?

### ISSUE THREAD

**Issue by mistahwolf** [MAFINS/MenyooSP#345]
_"...I do not update this project anymore as I am busy with other things.
...this went open-source under the GPLv3 licence was so that the community could update this, whether via revival projects using forks (persuant to the licence terms) or by creating merge/pull requests so that the main project can be updated with commits made by multiple individuals."_

So Mafins is officially done with Menyoo. But he has left it open source to 'multiple individuals' to update the main project. Buttloads of you guys out there know how to do this and still use this mod. I've used a couple of updates that were on 5Mods.com but they all got pulled for one reason or another. I would do it, but I know squat about coding and don't have the time to learn. So who's going to step up and make this happen?

**Comment by The-UnXplained** [comment]
Mafins stopped updating this menu a very long time ago.. when i asked him on the 5Mods about me taking it over and keeping it updated a few years ago, he more or less told me to do what i liked with it.. However, when i started updating it he kind of changed his mind and decided he wanted other people to only update it on here via pull request and went crying like a little baby to his admin and moderator friends on the 5mods website who banned me many times.. In my view, he only wants contributors on here to update it so he can continue to let everyone keep believing that he updates it.. however, it seem's most have since got wise to this and stopped.

I personally still continue to update it, and i would post a link to it on here.. but like this comment, he will most likely just delete it.. but i'm sure if you look hard enough you will find a link to it.. ;)

**Comment by Sethy1124** [comment]
@The-UnXplained maybe if you adhere to the GPL he wouldn't have you banned or delete your comments. It is clearly stated that if you release a modified version of a GPL licensed product, you _must_ release the source code, which you have not done.
https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic

**Comment by The-UnXplained** [comment]
@Sethy1124 - I was referring to conversations that took place some years ago on the shitty 5Mods website. 

As stated above, At the time, the guy told me to 'do what i liked' with it! but when i did just that, he changed his mind and made some changes on here. He now wants others to put in all the work on here so he can sit back, do nothing and let everyone continue to believe he updates it. - No doubt he will try deny all this soon or delete my comments..

**Comment by MAFINS** [comment]
@The-UnXplained Would appreciate it if you don't spread slander and misinformation. The licence was chosen and included since day 1. I have not told you to do what you liked with it. If you are to distribute, you must follow the rules. You must comply with its terms if you don't want your mediafire-uploaded binaries deleted. You're free to make a fork for a revival project or make pull requests to the main repo's master branch. I fail to understand why you can't do such simple things.

Frankly, I've been trying to convince everyone that I do not update it, and I don't want anyone believing otherwise. So you're so very wrong. My stance is clear. Follow the licence. Include your source code. Do you think I want someone downloading your version and taking the blame for any suspicious content within it? It's irrelevant whether or not it does, I cannot take your word. How have you not made a public fork on this website for your update and only provide links? That is incredibly dubious. On top of that, you're acting immature as if I know you or have banned you or taken any action personally. Any such links will be deleted.

**Comment by The-UnXplained** [comment]
Just for clarification, my old username on the 5mods site was 'soulreaver' and if i remember correctly the conversation was around 2019.. are you still suffering from memory loss..? nevermind, it doesn't matter to me i will continue to update and distribute it anyway for those who still want to use it and you can stick your rules, terms and licence where the sun don't shine. As for you 'trying to convince everyone that you don't update it' - so why don't you just add a simple credits section into the menu itself and give gredits to all the contributors..

**Comment by MAFINS** [comment]
@The-UnXplained No, I am not suffering from memory loss. However, you seem to have a tenuous grasp on the current terms, living in the past. You can choose to breach the terms and distribute it illegaly if you wish. You don't seem to care or have any sense of courtesy anyway. As for the credits section, anyone is free to build it. I already made my position clear but you seem to reinforce your outdated and idiosyncratic views. A CONTRIBUTING.md file is also welcome. I do not have an IDE or the game to test anything.

Regards
