### ISSUE TITLE
Slow loading of MP Clothes

### ISSUE THREAD

**Issue by ItzzVishal** [MAFINS/MenyooSP#381]
Clothes/Accessories loading slowly while changing mp clothes, anyone know how to fix it?

**Comment by mistahwolf** [comment]
That's been a thing since I started using Menyoo back in '17. Maffins never got around to addressing it. For me only 'lowr's' and 'feet' have the delay. Best way to get around it with Menyoo is to select what you want (i.e. 'Legs), select the color you want, then go back to the leg menu and then back to the item you selected. For whatever reason that advances the colors to the one you selected. You can also try waiting....
