### ISSUE TITLE
When is the update?

### ISSUE THREAD

**Issue by Master-Osa** [MAFINS/MenyooSP#384]
Hello MAFINS, when will you release a new version of the MenyooPC cheat menu?

**Comment by OmegAlex10** [comment]
There is an update on appveyor, but guess what. The devs of that site gave up (you can't download anything from it anymore), and yet again mafins still uploads updates there as if anyone on this planet can manually copy and paste his code into the .asi file! Look for community made menyoo updates or links to .asi files that were manually updated by a few people. Menyoo is kind of dead, it's up to the community to keep it working.

**Comment by Master-Osa** [comment]
Excuse me, I'm talking to you from an interpreter, did I understand you correctly? There is update 1.0.219 on the appveyor website, is this menyooPC update that can't be downloaded?

**Comment by Master-Osa** [comment]
Also, where can I find updates from the communities?

**Comment by OmegAlex10** [comment]
Mafins has actively updated menyoo on appveyor, but since the devs of appveyor themmselves ditched the appveyor project, everybody who attempts to download stuff from it will give an error "exceeded daily limit of 1024 MB" or something like that. On github the version is stuck at patch 2373, which is outdated. I'll give you a forum post with community  .asi's in a sec

**Comment by OmegAlex10** [comment]
https://forum.cfx.re/t/simple-trainer-wont-show-up/4183132/66
here, I also recommend reading the entire forum if your .asi core crashes, one of the devs on that forum found a fix for all .asi plugins that worked for me. If that won't be an issue, just download the corresponding .asi menyoo file (gta 5 patch wise)

**Comment by Master-Osa** [comment]
Thank you very much!

**Comment by OmegAlex10** [comment]
No problem!

**Comment by OmegAlex10** [comment]
They are available for fiveM and singleplayer, online gets you banned. And yes 1.7.0 is the current latest version that exists

**Comment by Master-Osa** [comment]
Thanks again!

**Comment by porcodio1234567** [comment]
> There is an update on appveyor, but guess what. The devs of that site gave up (you can't download anything from it anymore), and yet again mafins still uploads updates there as if anyone on this planet can manually copy and paste his code into the .asi file! Look for community made menyoo updates or links to .asi files that were manually updated by a few people. Menyoo is kind of dead, it's up to the community to keep it working.

no you retarded shit , it is up to mafins to update this mod menu

**Comment by porcodio1234567** [comment]
> Mafins has actively updated menyoo on appveyor, but since the devs of appveyor themmselves ditched the appveyor project, everybody who attempts to download stuff from it will give an error "exceeded daily limit of 1024 MB" or something like that. On github the version is stuck at patch 2373, which is outdated. I'll give you a forum post with community .asi's in a sec

that is fucking wrong , they must leave all the downloadable stuff there for whoever want to use it , for fuck sake , whatever they decided to do , the matherial must stay there for everyone's benefit

**Comment by porcodio1234567** [comment]
> There is an update on appveyor, but guess what. The devs of that site gave up (you can't download anything from it anymore), and yet again mafins still uploads updates there as if anyone on this planet can manually copy and paste his code into the .asi file! Look for community made menyoo updates or links to .asi files that were manually updated by a few people. Menyoo is kind of dead, it's up to the community to keep it working.

also , manyoo isn't dead or absent , i can guarantee you that he read each single report in this section , including my comments , asshole , in this period some people all over the internet are going insane , and they seem to only react to insults , other than that , they really feel like they are dead , but as soon as he will read my messages , you can bet you ass that he will react somehow , he is so brainwashed , like many other people , that he think shit such as "oh , since they can't force me to do anything , why should i care about wha they tell me ? why should i do things if they can't even force me?!!1?" see ? this is the level of stupidity we are dealing with , since we aren't forcing him in any way , he think , like various other assholes , that he don't have any good reason to be a decent person , this also explain why all of a sudden he stopped to update the fucking mod menu like there aren't a lot of people that wouldn't even spit over a video game is wasn't for the mods , but hey , we aren't forcing him , right ? so why he should give a fuck ? well , like i said , we are dealing with a fucking shit head , as whoever agree with his brocken record "none is obliged to update it" , well here is the big news , even if you mafins aren't at a gun point , you stll have to be a decent person who care about stuff , otherwise this is what happen , even the doctor who allowed that fucking bitch of your mother to allow your existent weren't somehow forced to do anything , he could have just left that stupud bitch daying in pain alone, with you dead inside her , but , he did what was right to do , fucking asshole brainwashed by satanists , we don't need to be forced to be decent people , fucking retarded , it is just shocking how modders look most of the times like handicapped people , that kind of handicapped people that have more brain than others for a specific thing , modding in this case , but for the rest are absolute shit heads , it doesn't take a genious to uderstand that you are supposed to guarantee this mod menu to be updated , not because someone is forcing you  ,but becuase it is right and important to do , but hey , if you assholes are that degraded , then you will be forced , no problem , if you are so willing to take out the worse in everyone because you are this fucking brocken record "none is obliged" , then so be it , be forced

**Comment by porcodio1234567** [comment]
> And the latest version 1.7.0 is suitable for a single game (not online)? Just as far as I understand, these versions of menyooPC are made for gta5 online for fiveM servers? (I just don't have a computer at hand right now) Thank you for answering so quickly!

the fucking link for that 1.7.0 version please ??????

**Comment by gofuckingkillyourselfyouretardedshit** [comment]
> There is an update on appveyor, but guess what. The devs of that site gave up (you can't download anything from it anymore), and yet again mafins still uploads updates there as if anyone on this planet can manually copy and paste his code into the .asi file! Look for community made menyoo updates or links to .asi files that were manually updated by a few people. Menyoo is kind of dead, it's up to the community to keep it working.

GO FUCKING KILL YOURSELF YOU RETARDED SHIT , YOU AND THE REST OF THE LOW LIFE ASSHOLES HERE DESERVE ALL THE INSULTS AND ALL THE PAIN AND TORTURE , INFACT THE NEXT STEP WILL BE TO FUCKING KILL ALL OF YOU PAINFULLY ALONG WITH THOSE WHO CAUSED YOU TO BE THE LOW LIFE TRASH THAT YOU ARE , YOU MUST KEEP FOR YOURSELF YOUR INSULTS , NOT BE , BECAUSE I AM RIGHT , AND YOU , YOU ARE WRONG ,YOU ARE CONDONING CARLESNESS AND EGOISM , SO YOU ARE THE PROBLEM HERE ,NOT THE , ASSHOLES LIKE YOU ESCAPED THE CONSEQUENCES OF THE THE MISERABLE CRAP THAT THEY ARE FOR WAY TOO LONG , AND WE ARE ALL PAYING THE CONSEQUENCES OF THIS , SO , TO BE CALLED OUT ON YOUR BULLSHT IS THE FUCKING MINIMUM TO EXPECT , YOU DAMN MORON

**Comment by The-UnXplained** [comment]
The original creator doesn't update this menu anymore, i do.. you can either use my updated version (link on my profile), wait forever for a contributor or update it yourself..

**Comment by occr** [comment]
> Hello MAFINS, when will you release a new version of the MenyooPC cheat menu?

mafins is updating the trainer , here  https://github.com/Hakkodevelopment/MenyooFiveM/releases , he just avoided to let everyone's here know about that

**Comment by occr** [comment]
> The original creator hasn't updated this menu himself for a very long time - you can either use my updated version (link on my profile), wait forever for a contributor to update it or learn to do it yourself!

shut up you fucking liar , i posted the link for the 1.7.0 version myself , go fucking kill yourself

**Comment by occr** [comment]
> https://forum.cfx.re/t/simple-trainer-wont-show-up/4183132/66 here, I also recommend reading the entire forum if your .asi core crashes, one of the devs on that forum found a fix for all .asi plugins that worked for me. If that won't be an issue, just download the corresponding .asi menyoo file (gta 5 patch wise)

go fucking kill yourself you retarded shit , menyoo is fucking updating the mod menu , i posted the link for it myself , fuckig dick head

**Comment by OmegAlex10** [comment]
> > The original creator hasn't updated this menu himself for a very long time - you can either use my updated version (link on my profile), wait forever for a contributor to update it or learn to do it yourself!
> 
> shut up you fucking liar , i posted the link for the 1.7.0 version myself , go fucking kill yourself

my god, you do realise that you insulted the developer of the mod you linked to? are you fucking crazy?

**Comment by OmegAlex10** [comment]
> > https://forum.cfx.re/t/simple-trainer-wont-show-up/4183132/66 here, I also recommend reading the entire forum if your .asi core crashes, one of the devs on that forum found a fix for all .asi plugins that worked for me. If that won't be an issue, just download the corresponding .asi menyoo file (gta 5 patch wise)
> 
> go fucking kill yourself you retarded shit , menyoo is fucking updating the mod menu , i posted the link for it myself , fuckig dick head

and can you stop being a complete hypocrite and a jerk? All you do is insult people for no reason, all because I was helpful? You're lashing out on people just because nobody else is "more correct than you are", which is literally what you describe us as, even tho you are the problem here. Stop insulting everyone for no reason, stop blaming others for lying even tho we did nothing but help each other, stop pretending that my solution is not the same as yours, for god sakes stop insulting the person you just linked to as "the real solution", stop being a child and grow the hell up!!! (last thing I'll ever say to you)

**Comment by The-UnXplained** [comment]
@occr I think you will find that version is by 'Hakkodevelopment' to work with FiveM.. ( ͡° ͜ʖ ͡°)

**Comment by piqle** [comment]
@The-UnXplained 

why isn't your source available if it's just a fork of @MAFINS ? kind of off-putting.
