### ISSUE TITLE
[BUG] ASI plugin does not claim to support game build 2699

### ISSUE THREAD

**Issue by Tamer173** [MAFINS/MenyooSP#385]
`[      4969] [b2699_GTAProce]             MainThrd/ Unable to load D:\Fivem\FiveM.app\plugins\Menyoo.asi - this ASI plugin does not claim to support game build 2699. If you have access to its source code, add `FX_ASI_BUILD 2699 dummy.txt` to the .rc file when building this plugin. If not, contact its maintainer.`

Bro is it not possible to add all the build verision no so that is dosent occurs and please fix this issue !

**Comment by porcodio1234567** [comment]
wow , what do they always say ? that we should learn to do all this ourselves ? implying that they would be more prone to help those who want to learn , yeah right , your comment here demontrated that they just don't care ragardless of who ask for help with the release of the update , or ask help to partecipate to the work for the update itself , see ? they still ignore you , they just don't care , do this little social experiment: do a post were you just insult them , you see that they will reply IMMEDIATELY , like , in some minutes they will just react , this tell you how asshole and stupid they are , to only react to insults and then complain when you insult them , and again , they are finally forced to stop with the bullshit of imply that they don't like to reply to people who just ask for the updates , because even with someone that is involved with the creation of the update itself , they just don't give a fuck about reply , see you fucking assholes ? you exposed yourselves without us have to do nothing , thanks for the help , and go fucking kll yourself , and remember of the fucking "we don't own you a thing so why we should care about be decent people who help and reply??1!" when YOU need help , you assholes will be there all in pain , hoping for someone to help , but noooo , because none is force to help you assholes , so why someone should help you if you aren't forced to ? dick heads , yes , even with no obligation , generosity is still a must , dicks

**Comment by Tamer173** [comment]
> wow , what do they always say ? that we should learn to do all this ourselves ? implying that they would be more prone to help those who want to learn , yeah right , your comment here demontrated that they just don't care ragardless of who ask for help with the release of the update , or ask help to partecipate to the work for the update itself , see ? they still ignore you , they just don't care , do this little social experiment: do a post were you just insult them , you see that they will reply IMMEDIATELY , like , in some minutes they will just react , this tell you how asshole and stupid they are , to only react to insults and then complain when you insult them , and again , they are finally forced to stop with the bullshit of imply that they don't like to reply to people who just ask for the updates , because even with someone that is involved with the creation of the update itself , they just don't give a fuck about reply , see you fucking assholes ? you exposed yourselves without us have to do nothing , thanks for the help , and go fucking kll yourself , and remember of the fucking "we don't own you a thing so why we should care about be decent people who help and reply??1!" when YOU need help , you assholes will be there all in pain , hoping for someone to help , but noooo , because none is force to help you assholes , so why someone should help you if you aren't forced to ? dick heads , yes , even with no obligation , generosity is still a must , dicks

Yo i fixed it with some research so don't be toxic and do something about your personality 🙂

**Comment by porcodio1234567** [comment]
> > wow , what do they always say ? that we should learn to do all this ourselves ? implying that they would be more prone to help those who want to learn , yeah right , your comment here demontrated that they just don't care ragardless of who ask for help with the release of the update , or ask help to partecipate to the work for the update itself , see ? they still ignore you , they just don't care , do this little social experiment: do a post were you just insult them , you see that they will reply IMMEDIATELY , like , in some minutes they will just react , this tell you how asshole and stupid they are , to only react to insults and then complain when you insult them , and again , they are finally forced to stop with the bullshit of imply that they don't like to reply to people who just ask for the updates , because even with someone that is involved with the creation of the update itself , they just don't give a fuck about reply , see you fucking assholes ? you exposed yourselves without us have to do nothing , thanks for the help , and go fucking kll yourself , and remember of the fucking "we don't own you a thing so why we should care about be decent people who help and reply??1!" when YOU need help , you assholes will be there all in pain , hoping for someone to help , but noooo , because none is force to help you assholes , so why someone should help you if you aren't forced to ? dick heads , yes , even with no obligation , generosity is still a must , dicks
> 
> Yo i fixed it with some research so don't be toxic and do something about your personality 🙂

go fucking kill yourself you retarded shit , i am not toxic , i am right , the ones who are toxic are the assholes who didn't replied to you , and you , because you are a moron for not understand this, in case isn't clear , i was supporting you , and no , we are not supposed to stay always calm no matter what happen , if people are disrespectful , if we are mistreated , we have all the right to go mad and do a mess , you don't get rude with someone by gnoring t's requests for help and then expect everyone to be so kind with you , understood you fucking retarded ? people must be treated as they treat others , those assholes , feel entitled to ignore us despite this very site only exist because there are those who aren't hackers , so it is perfectly useless to ignore us , and it is wrong
