### ISSUE TITLE
Cars Despawning

### ISSUE THREAD

**Issue by kenjieskz** [MAFINS/MenyooSP#516]
****Hey Developer, can you somehow upgrade your mod or add a feature for keeping any spawned vehicle from despawning. Whenever I'm far away and came back to my safehouse my DLC cars are despawned, same problem whenever I save my game and load. Please add a feature like vehicle persistence. Thanks.**** @MAFINS

**Comment by nomakewan** [comment]
If you are running SHVDN, press F4 to open the console. Then, while sitting in the car you want to be persistent, type this into the console:

`Game.Player.Character.CurrentVehicle.IsPersistent = true;`

Just as a stopgap measure so you can get immediate satisfaction.

Interestingly Menyoo does actually use the native SHVDN is using in its vehicle spawn code, but it appears they're using it with different parameters.

I am not familiar with Menyoo's development so I may be misunderstanding, but it appears to me by comparing SHVDN's implementation and Menyoo's implementation that line 104 of Submenus\VehicleSpawner.cpp should be `SET_ENTITY_AS_MISSION_ENTITY(newcar, 1, 1);` instead, and that should actually make a spawned vehicle properly persistent.

Or as OP suggested, have this native call be an option somewhere that can be toggled on/off.

**Comment by metoxys** [comment]
Proposal: put it into Vehicle Spawn Options, leave default as off to be consistent with existing releases

**Comment by nomakewan** [comment]
Turns out that Menyoo actually does offer persistence when spawning everything already, but then afterwards marks the spawned vehicle as no longer needed, thus removing the persistence. So the only thing that needed changing other than adding the appropriate toggle in the INI and Vehicle Spawner was a check for that setting before trying to mark as no longer needed. If it's set, then the 'mark as no longer needed' is merely skipped.
