### ISSUE TITLE
Spawn adder at menu startup

### ISSUE THREAD

**Issue by vbelevcev** [MAFINS/MenyooSP#542]
Spawn adder at menu startup even with a clean configuration

**Comment by nomakewan** [comment]
What? I don't know what this issue is talking about. Can you go into more detail?

**Comment by vbelevcev** [comment]
I have nothing more to add and it is clearly written

**Comment by nomakewan** [comment]
If you believe that, then I forsee this issue remaining open until the end of time (or you learn to code whatever it is you're talking about yourself, since clearly you understand what you're talking about, whichever comes first). Best of luck.

**Comment by vbelevcev** [comment]
What is not clear is that an adder car is created and sometimes not even 1 in a clean configuration without saving settings????

**Comment by nomakewan** [comment]
It's not clear because that's not how Menyoo works. Opening Menyoo doesn't create anything. I cannot replicate your report, which is why it doesn't make sense. There is no code that would spawn anything just by opening Menyoo, nor does anything spawn when I open it myself

I would wonder if you have a conflict with something else in your install, here.
